### ISSUE TITLE
What is the difference between type “-” and type “Other”?

### ISSUE THREAD

**Issue by takagi97** [D-X-Y/Awesome-AutoDL#30]
Hi, 
I'm new to NAS. And I want to know the difference between type “-” and type “Other”.
Thank you!

**Comment by D-X-Y** [comment]
Good question. For other, it means it is not gradient / RL/ EA / PD. For "-", it means I haven;t get a time to read it and classify its category

**Comment by D-X-Y** [comment]
Welcome to make a PR to correct "-" with the correct class.
