### ISSUE TITLE
New paper on CVPR 2020

### ISSUE THREAD

**Issue by yehuitang** [D-X-Y/Awesome-AutoDL#38]
Hi Xuanyi,
Thanks for the awesome paper list for NAS!

Here is our CVPR 2020 paper about NAS based on performance prediction.
Paper Title: A Semi-Supervised Assessor of Neural Architectures
Paper link: https://openaccess.thecvf.com/content_CVPR_2020/papers/Tang_A_Semi-Supervised_Assessor_of_Neural_Architectures_CVPR_2020_paper.pdf

Thanks!

**Comment by D-X-Y** [comment]
You are welcome. Your paper is added :)
