### ISSUE TITLE
Where is the library of PyGlove?

### ISSUE THREAD

**Issue by zhengxiawu** [D-X-Y/Awesome-AutoDL#39]
The Library PyGlove only have a neuralPS paper, not an usable Library, where is the code?

**Comment by D-X-Y** [comment]
It is currently a Google internal library, and will open source in some months.

**Comment by mekaneeky** [comment]
2022 and still nothing !

**Comment by D-X-Y** [comment]
Thanks for everyone's patience. I will post updates in this thread about PyGlove.

**Comment by Deathn0t** [comment]
Hello, Pyglove is indeed a nice framework. I inspired myself from it and created a similar package (open source) but also with different features. For example, more complex Python expressions are allowed on symbols (not only the Tree of arguments). If anyone is interested I am welcoming critics and contributions: https://github.com/deephyper/metalgpy

**Comment by D-X-Y** [comment]
FYI, @zhengxiawu PyGlove is now released at https://github.com/google/pyglove, we will release the website / manual / blog soon.

**Comment by mekaneeky** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face: :partying_face: :partying_face: :partying_face: :partying_face: :partying_face: :partying_face: :partying_face: :partying_face: :partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Comment by KeJunChao0222** [comment]
2023 and still nothing!
