### ISSUE TITLE
Zen-NAS ICCV 2021

### ISSUE THREAD

**Issue by MingLin-home** [D-X-Y/Awesome-AutoDL#52]
Dear D-X-Y,

We have one ICCV 2021 paper about zero-shot Neural Architecture Search:

paper arXiv link: https://arxiv.org/abs/2102.01063 

Github: https://github.com/idstcv/ZenNAS

It would so nice of you if you could kindly append this work to the paper list. Thank you very much!

**Comment by D-X-Y** [comment]
Sure, would u you mind also clarify the type of the method, differentiable or RL or evolution, as well as the utilized search space?

**Comment by MingLin-home** [comment]
Dear D-X-Y,

Zen-NAS is a zero-shot NAS method, meaning that it does not train any network parameter during the search. This is a novel way to search neural architectures, different from differentiable or RL methods which require parameter training of super-net or sampled structures.

We mostly consider two popular search spaces: a) ResNet-like search space which uses residual blocks; b) EfficientNet-like search space which uses depth-wise convolution and inverse bottleneck.

Many thanks ahead!

**Comment by D-X-Y** [comment]
Added, nice work!
